from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np

try:
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import (
        accuracy_score,
        f1_score,
        precision_score,
        recall_score,
    )
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC
except ImportError as exc:  # pragma: no cover - handled at runtime
    raise SystemExit(
        "scikit-learn is required for this script. Install it with:\n"
        "  pip install scikit-learn"
    ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train baseline classifiers on extracted SpA-MMD features."
    )
    parser.add_argument(
        "--features_csv",
        type=Path,
        required=True,
        help="CSV generated by extract_spa_mmd_features.py",
    )
    parser.add_argument(
        "--train_split",
        type=Path,
        required=True,
        help="Subject list for training.",
    )
    parser.add_argument(
        "--test_split",
        type=Path,
        required=True,
        help="Subject list for testing.",
    )
    parser.add_argument(
        "--task",
        choices=("disease", "severity"),
        default="disease",
        help="Prediction task to train.",
    )
    parser.add_argument(
        "--model",
        choices=("logreg", "svm"),
        default="logreg",
        help="Baseline model type.",
    )
    return parser.parse_args()


def _read_split(path: Path) -> set[str]:
    subjects = set()
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            value = line.strip()
            if not value or value.startswith("#"):
                continue
            subjects.add(value.split("/")[0])
    return subjects


def _load_features(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _split_rows(rows: list[dict[str, str]], train_subjects: set[str], test_subjects: set[str]):
    train_rows = []
    test_rows = []
    for row in rows:
        subject = row["subject_id"]
        if subject in train_subjects:
            train_rows.append(row)
        elif subject in test_subjects:
            test_rows.append(row)
    if not train_rows or not test_rows:
        raise SystemExit("Train/test split resulted in empty rows.")
    return train_rows, test_rows


def _build_matrix(rows: list[dict[str, str]], task: str):
    ignore_keys = {"subject_id", "session", "disease_label", "severity_label"}
    feature_keys = [key for key in rows[0].keys() if key not in ignore_keys]
    x = np.asarray([[float(row[key]) for key in feature_keys] for row in rows])
    if task == "disease":
        y = np.asarray([int(row["disease_label"]) for row in rows])
    else:
        y = np.asarray([int(row["severity_label"]) for row in rows])
    return x, y, feature_keys


def _build_model(model_name: str):
    if model_name == "svm":
        clf = SVC(kernel="rbf", class_weight="balanced")
    else:
        clf = LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            solver="liblinear",
        )
    return Pipeline([("scaler", StandardScaler()), ("clf", clf)])


def main() -> None:
    args = parse_args()
    rows = _load_features(args.features_csv)
    train_subjects = _read_split(args.train_split)
    test_subjects = _read_split(args.test_split)
    train_rows, test_rows = _split_rows(rows, train_subjects, test_subjects)

    x_train, y_train, feature_keys = _build_matrix(train_rows, args.task)
    x_test, y_test, _ = _build_matrix(test_rows, args.task)

    model = _build_model(args.model)
    model.fit(x_train, y_train)
    preds = model.predict(x_test)

    if args.task == "disease":
        print(f"accuracy={accuracy_score(y_test, preds):.4f}")
        print(f"precision={precision_score(y_test, preds, zero_division=0):.4f}")
        print(f"recall={recall_score(y_test, preds, zero_division=0):.4f}")
        print(f"f1={f1_score(y_test, preds, zero_division=0):.4f}")
    else:
        print(f"accuracy={accuracy_score(y_test, preds):.4f}")
        print(f"macro_f1={f1_score(y_test, preds, average='macro', zero_division=0):.4f}")

    print(f"num_features={len(feature_keys)}")
    print(f"train_rows={len(train_rows)} test_rows={len(test_rows)}")


if __name__ == "__main__":
    main()
